name: 🛠 Template Validate

on:
  push:
  pull_request:
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: nuclei install
        run: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

      - name: Template Validation
        run: |
          cp -r ${{ github.workspace }} $HOME
          nuclei -duc -validate -allow-local-file-access
